### ISSUE TITLE
Searches via UI returned no vertices of any type.  

### ISSUE THREAD

**Issue by packet-rat** [stucco/demo#6]
[Stucco Demo](https://github.com/stucco/demo/tree/master) 

After successfully building, populating, and "upping" Demo instantiation,  Searches via UI returned no vertices of any type.  

A number of rt errors were noted - samples in [Gist](https://gist.github.com/packet-rat/dc97efb2e9d200c46e8a3b461ceb9517) 

Rebooted VM.  Problem Cleared

**Comment by mikeiannacone** [comment]
Closing old issue, don't think this applies to recent versions (1.0+)
