### ISSUE TITLE
could not find stucco-virtualbox.box file

### ISSUE THREAD

**Issue by ydmydm** [stucco/demo#7]
I'm tying to setup project stucco/demo.But i could not find stucco-virtualbox.box file

**Comment by mikeiannacone** [comment]
It sounds like you're trying to build the `stucco-virtualbox.box` file as described in the readme?  Do you have any more specific information about your error?

**Comment by ydmydm** [comment]
I'm try to run command:vagrant box add ./stucco-virtualbox.box --name=stucco/stucco-ubuntu1404. Its said could not find stucco-virtualbox.box file
![20171110102637](https://user-images.githubusercontent.com/33323079/32640015-86256872-c601-11e7-849e-b651f7249f88.png)
